---
- name: Check for algorand-indexer
  ansible.builtin.stat:
    path: /usr/local/bin/algorand-indexer
  register: __indexer_check

- name: Install from Source
  ansible.builtin.import_tasks: install-from-source.yml
  when: not __indexer_check.stat.exists and indexer_install_from_source | bool

- name: Configure algorand-indexer
  ansible.builtin.import_tasks: configure.yml
